package br.com.k19.android.cap03.meretrizesaplication;

public enum Categoria {

    PICAPAU,KINGSMAN,MEUMALVADOFAVORITO,MYLITTLE,ITCOISA,DEVOLTA,EMOJI,ALEMMORTE,DIVINA,NOZES,AMORTE,BLADE,LEGO,CUECA,TEMPESTADE,UMARAZAO,ENTREIRMAS,PIORALUNO

}